### PR TITLE
Update pyvrp.repair operator interface to use lists of routes, not solutions

### LINKED ISSUE #389: Allow empty routes in Solution
I would like `Solution -> Solution`, but we need the ability to at least increase the number of routes somehow. Else we're unnecessarily limiting any LNS to never increase the number of routes, which seems weird to me (if the vehicles are available, why not?).

But `Solution` currently isn't equipped to do that. So we'd have to change that first, and then settle on a single interface for the repair operators.

_Originally posted by @N-Wouda in https://github.com/PyVRP/PyVRP/issues/386#issuecomment-1714551995_

### PR DESCRIPTION
**Pull request by N-Wouda**
This PR:

- [x] Closes #389.
- [x] Adds and passes relevant tests.
- [x] Has well-formatted code and documentation.

<details>

**Notes**:

- It is essential that you add a test when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by N-Wouda** [comment]
This PR is either part of #389, or it closes it, depending on whether we want to keep that issue open. I'm leaning close.

**Review by leonlan — APPROVED** [review]
LGTM

**Review by wouterkool — APPROVED** [review]
LGTM!

Only one remark but not necessarily related to this change: is `repair` the best terminology? It suggests the solution must be damaged/destroyed somehow, whereas I wonder if in general `greedy` and `nearest_route_insert` could also be used to construct a solution/insert new customers into existing solution, etc. If you agree, maybe consider renaming the module to 'construction' or something like that?

**Comment by N-Wouda** [comment]
> is `repair` the best terminology?

The main reason these operators exist is #307. There is a long tradition in LNS to call this step _repair_. That the operators in `pyvrp.repair` can do more things than just LNS is nice, but I'm a little hesitant to change the naming of this module on the basis of it being a big more general than just LNS.

**Pull request merged**
