### PR TITLE
Separate distance and duration matrices

### LINKED ISSUE #60: Rename distance_matrix to (travel_)duration_matrix
Hadn't really given this much thought, but everything's of course in time units, so we shouldn't talk about a "distance matrix" so much. We need to update a few places in the code to reflect this.

### LINKED ISSUE #184: Can we directly pass distance/time matrix as input to the ProblemData?
I always wonder can we directly pass distance/time matrix as input to the ProblamData instead of current co-ordinates informations. I guess it will results in different set of routes. Any suggestions! Thank you!

### PR DESCRIPTION
**Pull request by N-Wouda**
Adds support for separate distance and duration matrices. This PR:
- [x] Closes #184, closes #60;
- [x] Adds and passes relevant tests.
- [x] Has well-formatted code and documentation.

<details>

**Notes**:

- It is essential that you add a test when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by N-Wouda** [comment]
A bit of a work in progress.

**Comment by N-Wouda** [comment]
OK, I think content-wise we're mostly there. I still need to write tests, but I'll do that tomorrow I think.

**Comment by N-Wouda** [comment]
@wouterkool @leonlan I think this is ready for review. The number of tests is somewhat small, but they do cover the main points. Let me know what you think!

**Review by leonlan — APPROVED** [review]
LGTM!

**Review by wouterkool — COMMENTED** [review]
This looks great to me!

Only comment I have regards naming: compared to `dist` vs `distance`, I think `dur` is less self-explanatory than `duration`, which was what we previously implemented and discussed about [here](https://github.com/PyVRP/PyVRP/pull/169/files#diff-31568c78ee510de7ac71543baaee754f3bc38bcd323727c4c10561f290ae0b47). Also, to avoid things like `legDuration = duration()` would it be an idea to refer to the duration matrix as `durationMatrix`/`durationMat`/`durMat` rather than `duration` (same for distance matrix?)?

**Comment by N-Wouda** [comment]
> Only comment I have regards naming: compared to `dist` vs `distance`, I think `dur` is less self-explanatory than `duration`, which was what we previously implemented and discussed about [here](https://github.com/PyVRP/PyVRP/pull/169/files#diff-31568c78ee510de7ac71543baaee754f3bc38bcd323727c4c10561f290ae0b47). 

Done. Also resolved several cases where we were already using `time`, `dur` for this.

> Also, to avoid things like `legDuration = duration()` would it be an idea to refer to the duration matrix as `durationMatrix`/`durationMat`/`durMat` rather than `duration` (same for distance matrix?)? It's just a suggestion, I'm fine keeping it as is.

Can't really be helped; `duration` is a data member of `TimeWindowSegment`, so we need a different name regardless. I have renamed the `dur` argument to `durationMatrix`.

**Pull request merged**
