### PR TITLE
Add DistanceSegment

### LINKED ISSUE #330: Max distance for vehicles
#### Describe the solution you'd like
We do not currently support a constraint on the maximum distance a vehicle is allowed to travel.

#### Describe alternatives you have considered
None.

#### Additional context
We should probably do this via the penalty system, since small violations early on need not be problematic.

### PR DESCRIPTION
**Pull request by N-Wouda**
This PR adds a distance segment structure that is essentially a concatenation scheme for distance-related changes. The next step after this is the introduction of a max-distance constraint for #330. As such, this PR:

- [x] Adds and passes relevant tests.
- [x] Has well-formatted code and documentation.

TODO:
- [x] Add `DistanceSegment` to `pyvrp::search::Route` and the proxies there;
- [x] Rewrite the operators to use it (and perhaps simplify a bit?);
- [x] Profile/improve speed a bit;
- [x] Benchmark.

### Benchmarks

This PR (aa1b1008f40ec7864f8fd88ec34a4839315badfe; job ID 7339165; 1h VRPTW):
```
               MEAN      MIN      MAX   COV
      inst
obj   C1    41385.9  41341.2  41412.2   0.1
      C2    16196.8  16192.9  16201.3   0.0
      R1    47361.5  47329.2  47402.5   0.1
      R2    27796.2  27766.9  27863.8   0.1
      RC1   44328.7  44289.3  44379.9   0.1
      RC2   23280.6  23254.7  23305.1   0.1
iters C1    48148.1  37462.8  53355.0   9.9
      C2    74614.4  65722.2  79767.4   5.8
      R1    22659.1  19286.8  24750.3   7.2
      R2    45476.6  34275.2  51136.2  10.8
      RC1   23657.6  17187.2  26393.1  11.2
      RC2   48343.5  33959.3  58083.1  13.6
```

Current main (710fb3cae0695f683a7910dbae91200533128143; job ID 7336601; 1h VRPTW):
```
               MEAN      MIN      MAX   COV
      inst
obj   C1    41386.2  41375.2  41423.5   0.0
      C2    16196.1  16190.4  16201.5   0.0
      R1    47369.5  47314.0  47434.9   0.1
      R2    27800.9  27766.2  27861.3   0.1
      RC1   44332.2  44302.5  44364.6   0.0
      RC2   23285.9  23253.0  23318.2   0.1
iters C1    52380.4  45103.0  61356.0  10.5
      C2    81987.2  67216.5  98799.8  13.1
      R1    21873.4  17963.5  27184.1  13.6
      R2    41257.4  32528.4  50544.3  16.0
      RC1   23474.1  18713.9  29652.3  15.1
      RC2   43841.6  33209.8  55092.1  16.3
```

<details>

**Notes**:

- It is essential that you add a test when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by N-Wouda** [comment]
This implementation is about 1/3rd slower than current main, but I haven't really focused on performance yet. I'll have a look later today to see what can be gained further.

**Comment by N-Wouda** [comment]
I'll continue speeding this up later. I'm pretty sure we can get close to parity with current main already in this PR, and hopefully do better once we start deduplicating everything.

**Comment by N-Wouda** [comment]
Performance should be OK now, and might even be a bit better than current main.

**Comment by N-Wouda** [comment]
Benchmarks look fine. I'll have another look tomorrow but this should be good to go now. @leonlan could you also have a look? There's some duplication here that wasn't too obvious before when we used the `ProblemData::dist` member everywhere, but I'll try to clean that up in a follow-up PR.

**Review by leonlan — APPROVED** [review]
LGTM!

**Pull request merged**
