### PR TITLE
Add support for reading MDVRPTW instances

### PR DESCRIPTION
**Pull request by N-Wouda**
This PR:

- [x] Is part of #305, #252.
- [x] Adds and passes relevant tests.
- [x] Has well-formatted code and documentation.

See https://github.com/PyVRP/Instances/pull/6 for the instances this is meant to read.

### Benchmark on MDVRPTW

A bit of a try-out (345da5ad5f524ac3b246018a316c7c27881350c6; 10x seeds; 1h; job ID 6963529):
```
              MEAN      MIN      MAX  COV
    inst
obj PR11A   6670.5   6659.1   6678.7  0.1
    PR11B   4816.6   4814.6   4825.4  0.1
    PR12A   8183.7   8159.9   8205.2  0.2
    PR12B   6030.0   6016.4   6041.8  0.2
    PR13A   9568.1   9545.6   9616.2  0.2
    PR13B   7229.8   7216.5   7259.7  0.2
    PR14A  11023.9  10981.6  11067.7  0.2
    PR14B   8723.8   8690.6   8742.9  0.2
    PR15A  12862.2  12795.5  12949.7  0.3
    PR15B  10326.8  10291.2  10364.1  0.3
    PR16A  14199.2  14091.5  14302.3  0.5
    PR16B  11380.2  11333.2  11427.8  0.3
    PR17A   6295.7   6292.6   6302.3  0.1
    PR17B   4773.9   4771.2   4782.4  0.1
    PR18A   8232.7   8211.7   8253.1  0.2
    PR18B   6470.3   6459.5   6487.9  0.2
    PR19A  10624.8  10580.7  10672.2  0.2
    PR19B   8142.3   8119.4   8171.0  0.3
    PR20A  11808.5  11753.0  11871.6  0.3
    PR20B  10140.4  10102.5  10177.9  0.3
    PR21A   6238.3   6234.4   6254.7  0.1
    PR21B   4830.3   4822.4   4840.5  0.1
    PR22A   7942.4   7910.7   7981.6  0.3
    PR22B   6448.3   6422.8   6479.8  0.3
    PR23A   9853.1   9771.4   9933.5  0.4
    PR23B   8402.0   8362.9   8430.6  0.3
    PR24A  11832.8  11747.0  11953.4  0.5
    PR24B  10612.2  10570.0  10642.6  0.2
```

Relevant comparison (Table 8 of [Vidal et al. (2013)](https://doi.org/10.1016/j.cor.2012.07.018)):
image

<details>

**Notes**:

- It is essential that you add a test when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by N-Wouda** [comment]
We'll need to think of a way to write solutions for these instances next, but I think that can be done outside of this PR (instead, in e.g. #252).

**Comment by N-Wouda** [comment]
@leonlan can you review this in tandem with https://github.com/PyVRP/Instances/pull/6?

**Review by leonlan — APPROVED** [review]
LGTM!

**Comment by N-Wouda** [comment]
Benchmark's running! 🤞

**Comment by N-Wouda** [comment]
Didn't quite work. When running locally I could not really figure this one out, but it could be due to the size of some of the data values (which might at some point exceed what `int` can handle). I've updated the data to return to just floats, and am now running a benchmark in double precision.

**Comment by N-Wouda** [comment]
This worked, and is substantially better than the baseline results. I don't know if they're reliable (this being our first time running them), but I cannot think of any reason why they would not be.

All in all I'm pretty happy with this. Let's merge this in, and then think about how we ought to do our benchmarking for MDVRPTW.

**Comment by leonlan** [comment]
Results look really good. Nice!

**Pull request merged**
