### PR TITLE
Add PyVRP/Instances submodule

### PR DESCRIPTION
**Pull request by N-Wouda**
This PR adds a submodule for self-hosted instances, rather than assuming the user can download these. This is not that relevant for CVRPLIB instances, but will become more important when we need benchmarks for problem variants where no good external defaults exist (e.g., prize collecting in https://github.com/PyVRP/Instances/pull/1).

<details>

**Notes**:

- It is essential that you add a test when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by N-Wouda** [comment]
@wouterkool @leonlan I think we can also add the 100 final Euro/NeurIPS instances to https://github.com/PyVRP/Instances?

**Review by leonlan — APPROVED** [review]

**Comment by leonlan** [comment]
> We'd have to update them;

We should not do it for CVRPLIB instances, because they are keeping track of the BKS themselves. But I'm in favor of doing it for instances that we maintain ourselves, e.g., the PCVRP instances. We could set up a BKS submission workflow and let other users submit PRs with the new best solutions.

**Comment by N-Wouda** [comment]
I think that's a reasonable default. We provide BKS for benchmark instances that do not exist elsewhere, and assume users can obtain BKSs for instances maintained by outside parties (e.g., CVRPLIB).

**Comment by leonlan** [comment]
> @wouterkool @leonlan I think we can also add the 100 final Euro/NeurIPS instances to [PyVRP/Instances](https://github.com/PyVRP/Instances)?
> 
> (if we use those for benchmarking)

Forgot the reply on this one. I don't think we should use Euro/NeurIPS instances for benchmarking because they are too small (most are 200-500 customers) and they not established yet in the literature. 

I do think there is a need for new VRPTW benchmark instances, perhaps by making larger instances based on the Euro-NeurIPS data. I suggested this to @wouterkool a long time ago, are there any plans to work on that?

**Comment by N-Wouda** [comment]
I'm going to merge this in for now

> Forgot the reply on this one. I don't think we should use Euro/NeurIPS instances for benchmarking because they are too small (most are 200-500 customers) and they not established yet in the literature.

Sure, although I don't think very small instances are useless (if anything to check we can solve those almost all to (near) optimality). But if we do want small instances, other established benchmarks might be a better go-to.

**Comment by N-Wouda** [comment]
I think we can merge this in soon. The prize-collecting instances are also mostly done (in https://github.com/PyVRP/Instances/pull/1), but we do not need to wait for that to merge this.

**Pull request merged**
