### PR TITLE
Benchmarks v0.4.2

### PR DESCRIPTION
**Pull request by leonlan**
This PR updates the benchmark for v0.4.2.

### CODE REVIEW

**Comment by leonlan** [comment]
Pretty significant drop in performance on CVRP instances (0.25% -> 0.37%). This also holds for V0.4.0.

**Comment by N-Wouda** [comment]
This is w.r.t. to the BKS on 28/2/23 right? We should probably add a note of some sorts to the page to describe why we do that.

Should we mention that we changed computer clusters between 0.3.0 and 0.4.2?

**Comment by leonlan** [comment]
> This is w.r.t. to the BKS on 28/2/23 right? We should probably add a note of some sorts to the page to describe why we do that.

It's w.r.t. the most recent BKS but they're the same as 28/2/23.

> Should we mention that we changed computer clusters between 0.3.0 and 0.4.2?

I actually realize that made a mistake due to migration. I rewrote some scripts and I forgot to use the "cvrp.toml" config for the CVRP benchmark. I'm going to run this benchmark again.

**Comment by N-Wouda** [comment]
> I actually realize that made a mistake due to the migration. I rewrote some scripts and I forgot to use the "cvrp.toml" config for the CVRP benchmark. I'm going to run this benchmark again.

Oh, that could well be it!

**Comment by N-Wouda** [comment]
> It's w.r.t. the most recent BKS but they're the same as 28/2/23.

I feel like we need to clarify this somehow/somewhere. If our performance remains the same but the BKS do change, it looks like we're getting worse w.r.t. previous versions of PyVRP - even though that need not be the case at all. When the BKS do change we might want to add a column that compares to the BKS as they were when we started benchmarking (28/2/23), and the BKS as they are at the time of release. Something to circle back to later when it's actually relevant.

**Comment by leonlan** [comment]
It indeed turned out to be the configuration file: the gap with the `cvrp.toml` config file is 0.18%.

**Review by N-Wouda — APPROVED** [review]

**Comment by N-Wouda** [comment]
LGTM. Let's wait for the docs build to see if the table now renders correctly, and then we can merge it in. 

Thanks!

**Pull request merged**
