### PR TITLE
Print solver progress

### LINKED ISSUE #455: Output solver progress
#### Is your feature request related to a problem? Please describe
There is currently no real-time feedback about the solver progress. This leaves the user in the dark about how the solver is doing; the solver might have converged already, and the user won't know until they investigate the statistics. 

It's common for many solvers like Gurobi and CPLEX to output the solver progress to the console like this:

<details>
<summary>Example</summary>

```
 ! --------------------------------------------------- CP Optimizer 22.1.1.0 --
 ! Minimization problem - 15586 variables, 31679 constraints
 ! Presolve      : 7195 extractables eliminated
 ! TimeLimit            = 100
 ! LogVerbosity         = Terse
 ! SearchType           = IterativeDiving
 ! Initial process time : 0.18s (0.18s extraction + 0.00s propagation)
 !  . Log search space  : 38467.7 (before), 38467.7 (after)
 !  . Memory usage      : 62.9 MB (before), 62.9 MB (after)
 ! Using parallel search with 8 workers.
 ! ----------------------------------------------------------------------------
 !          Best Branches  Non-fixed    W       Branch decision
                        0      15586                 -
 + New bound is 9702
 *         83128    20007  23.24s       1      (gap is 88.33%)
           83128    36858        921    6            -
 + New bound is 39749 (gap is 52.18%)
 *         83058    43066  31.68s       6      (gap is 52.14%)
 *         74197    36598  32.25s       3      (gap is 46.43%)
 ```

</details>

We already have access to data like incumbents, solver time and iterations since we collect statistics by default.

#### Describe the solution you'd like
I would like to have `Model.solve` interface output the solver progress. The desired behavior is to set some argument like `log=True` to output the solver progress. I even think logging should be the default.

The simplest version should output the following each time a new best solution is found:
- Incumbent (best feasible solution)
- Time (elapsed solving time)
- Iterations (elapsed number of iterations)

We can also have more verbose variants, which output more statistics or output logs on different events (e.g., population restart).

#### Describe alternatives you have considered
N/A

### PR DESCRIPTION
**Pull request by leonlan**
This PR adds support for printing solver progress. This is enabled by default when solving through the Model interface, but not for GA itself. As such, this PR:

- [x] Closes #455.
- [x] Adds and passes relevant tests.
- [x] Has well-formatted code and documentation.

### CODE REVIEW

**Comment by leonlan** [comment]
The output looks like this now:

```
---------------------------------- PyVRP v0.8.0a0 ----------------------------------

Solving an instance with 1 depot, 1000 clients, and 250 vehicles.

--------------------------------- Solver progress ----------------------------------

        Statistics         |          Feasible          |         Infeasible        
  Iters   T (s)       Best | Size        Avg       Best | Size        Avg       Best

    500   20.32     479443 |   35   485108.2     479443 |   63  962815.03     477490
   1000   38.39     476639 |   29  483689.69     476639 |   62  1145673.5     475795
   1500   57.67     473231 |   56  479492.73     473231 |   60  842477.15     473860
   2000   75.91     471745 |   54  475801.57     471745 |   52  788709.33     469761
   2500   93.25     469561 |   60  474159.37     469561 |   52  472674.92     468855

------------------------------------- Summary --------------------------------------

Search terminated after 2704 iterations and 100.00 seconds.
Best-found solution has cost 468716.

--------------------------------------- End ----------------------------------------
```

**Comment by N-Wouda** [comment]
I've split off the logging from the GA itself for now. Next steps are thinking about what to print, the interface, and add tests.

**Comment by N-Wouda** [comment]
I'm working towards Gurobi-style logs. That's still a while off, but this is what I have so far:
```
PyVRP v0.6.3

Solving an instance with 1 depot, 100 clients, and 100 vehicles.

                |        Feasible        |       Infeasible
  Iters    Time | Size      Avg     Best | Size      Avg     Best
    500      2s |   43   281315   277073 |   46   279403   276050
   1000      3s |   61   278378   276099 |   50   276280   275119
   1500      4s |   36   277659   276099 |   57   276414   274916
   2000      5s |   62   277619   276099 |   62   276234   274916
   2500      6s |   39   277060   275944 |   26   276911   274761
   3000      7s |   32   276762   275928 |   32   275768   274745
   3500      8s |   64   277310   275928 |   40   275843   274745
   4000      9s |   63   278314   275928 |   48   276433   274411
   4500     10s |   53   279372   275928 |   55   277023   274411

Search terminated after 4646 iterations and 10s.
Best-found solution has cost 275928.
```
I'm trying to make some space in the table for additional information.

**Comment by N-Wouda** [comment]
I think this is a pretty reasonable first attempt. All that's left is to finalise the interface and write more tests.

**Review by N-Wouda — APPROVED** [review]

**Comment by N-Wouda** [comment]
@leonlan can you review this?

**Comment by leonlan** [comment]
LGTM!

**Pull request merged**
